export const gameData = {
    Germany: 'Berlin',
    Azerbaijan: 'Baku',
    Austria: 'Vienna',
    Belarus: 'Minsk',
    Belgium: 'Brussels',
    Croatia: 'Zagreb',
    Czechia: 'Prague',
    Denmark: 'Copenhagen',
    Estonia: 'Tallinn',
    Finland: 'Helsinki',
    France: 'Paris',
    Greece: 'Athens',
    Hungary: 'Budapest',
    Iceland: 'Reykjavik',
    Ireland: 'Dublin',
    Italy: 'Rome',
    Latvia: 'Riga',
    Liechtenstein: 'Vaduz',
    Lithuania: 'Vilnius',
    Luxembourg: 'Luxembourg',
    Malta: 'Valletta',
    Moldova: 'Chisinau',
    Monaco: 'Monaco',
    Montenegro: 'Podgorica',
};
